---
openapi: 3.0.1
info:
  title: defaultTitle
  description: defaultDescription
  version: "1.0"
servers:
- url: http://0.0.0.0
paths:
  /api/V1/user/login:
    post:
      tags:
        - User
      description: The user login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_login_body'
            examples:
              "0":
                value: |-
                  {
                      "email": "prova@example.net222",
                      "password": "fsamofas"
                  }
      responses:
        "200":
          description: Valid response shold contain status OK and the token inside response['data']['token']
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                "0":
                  value: '{"status":"OK","data":{"token":"8|PyVCiSvzjLC1tKOr9eSRPn2GawJCFPLqfp9A8lVW","user":{"id":1,"name":"Abdullah Collins IV","email":"prova@example.net","email_verified_at":"2022-04-17T16:06:28.000000Z","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","deleted_at":null}}}'
        "400":
          description: Example error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
              examples:
                "0":
                  value: '{"error":"Login Failed"}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
  /api/V1/cart/{cartId}:
    get:
      tags:
        - Cart
      description: You shold obtain the content of a your own cart. CartId is an integer
      responses:
        "200":
          description: OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
              examples:
                "0":
                  value: '{"status":"OK","data":{"cart":{"id":2,"user_id":1,"name":"Aryanna Murphy","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","products":[{"sku":"beatae-corrupti-repudiandae-ducimus-eos-quis","name":"fugit numquam","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","price":"5.00"},{"sku":"porro-labore-quae-neque-aspernatur-eius-quas","name":"blanditiis omnis","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","price":"1.00"}]}}}'
        "404":
          description: Error example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              examples:
                "0":
                  value: '{"message":"Item not found"}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
  /api/V1/cart/products:
    post:
      tags:
        - Product
      description: Insert product in a cart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cart_products_body'
            examples:
              "1":
                value: |-
                  {
                      "cart": 2,
                      "skus": ["no-exist"]
                  }
              "0":
                value: |-
                  {
                      "cart": 2,
                      "skus": ["example-sku"]
                  }
      responses:
        "200":
          description: Ok response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              examples:
                "0":
                  value: '{"status":"OK","data":{"message":"Product added successfully"}}'
        "422":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
              examples:
                "0":
                  value: '{"message":"The selected skus.0 is invalid.","errors":{"skus.0":["The selected skus.0 is invalid."]}}'
      servers:
      - url: http://0.0.0.0
    delete:
      tags:
        - Product
      description: Remove product
      responses:
        "200":
          description: Success example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              examples:
                "0":
                  value: '{"status":"OK","data":{"message":"Product removed successfully"}}'
        "422":
          description: Error example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
              examples:
                "0":
                  value: '{"message":"The selected skus.0 is invalid.","errors":{"skus.0":["The selected skus.0 is invalid."]}}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
  /api/V1/cart:
    post:
      tags:
        - Cart
      description: Create cart example
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1_cart_body'
            examples:
              "0":
                value: |-
                  {
                      "name": "fsafsafas",
                      "skus": ["example-sku232"]
                  }
      responses:
        "200":
          description: OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
              examples:
                "0":
                  value: '{"status":"OK","data":{"id":34}}'
        "422":
          description: Error example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
              examples:
                "0":
                  value: '{"message":"The selected skus.0 is invalid.","errors":{"skus.0":["The selected skus.0 is invalid."]}}'
      servers:
      - url: http://0.0.0.0
    delete:
      tags:
        - Cart
      description: Delete cart example
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1_cart_body'
            examples:
              "0":
                value: |-
                  {
                      "cart": 15
                  }
              "1":
                value: |-
                  {
                      "cart": 1
                  }
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              examples:
                "0":
                  value: '{"status":"OK","data":{"message":"Cart deleted successfully"}}'
        "422":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422_1'
              examples:
                "0":
                  value: '{"message":"The selected cart is invalid.","errors":{"cart":["The selected cart is invalid."]}}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
  /api/V1/carts/:
    get:
      tags:
        - Cart
      description: Get all carts
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
              examples:
                "0":
                  value: '{"status":"OK","data":{"carts":[{"id":2,"user_id":1,"name":"Aryanna Murphy","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","deleted_at":null,"products":[{"sku":"beatae-corrupti-repudiandae-ducimus-eos-quis","name":"fugit numquam","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","price":"5.00"},{"sku":"porro-labore-quae-neque-aspernatur-eius-quas","name":"blanditiis omnis","created_at":"2022-04-17T16:06:28.000000Z","updated_at":"2022-04-17T16:06:28.000000Z","price":"1.00"}]},{"id":33,"user_id":1,"name":"fsafsafas","created_at":"2022-04-18T07:37:29.000000Z","updated_at":"2022-04-18T07:37:29.000000Z","deleted_at":null,"products":[{"sku":"example-sku","name":"eum illum","created_at":"2022-04-17T16:06:30.000000Z","updated_at":"2022-04-17T16:06:30.000000Z","price":"6.00"}]},{"id":34,"user_id":1,"name":"fsafsafas","created_at":"2022-04-18T08:16:53.000000Z","updated_at":"2022-04-18T08:16:53.000000Z","deleted_at":null,"products":[{"sku":"example-sku","name":"eum illum","created_at":"2022-04-17T16:06:30.000000Z","updated_at":"2022-04-17T16:06:30.000000Z","price":"6.00"}]}]}}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
  /api/V1/user/logout:
    post:
      tags:
        - User
      description: Logout
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
              examples:
                "0":
                  value: '{"status":"OK","data":{"status":"OK","message":"Logged Out"}}'
        "401":
          description: If not logged it will give an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              examples:
                "0":
                  value: '{"message":"Unauthenticated."}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
  /api/V1/user/register:
    post:
      tags:
        - User
      description: Registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_register_body'
            examples:
              "0":
                value: |-
                  {
                      "email": "prova@example.net",
                      "password": "fsamofas"
                  }
      responses:
        "422":
          description: Error Messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422_2'
              examples:
                "0":
                  value: '{"message":"The name field is required. (and 1 more error)","errors":{"name":["The name field is required."],"email":["The email has already been taken."]}}'
                "1":
                  value: '{"message":"The email has already been taken.","errors":{"email":["The email has already been taken."]}}'
      servers:
      - url: http://0.0.0.0
    servers:
    - url: http://0.0.0.0
components:
  schemas:
    inline_response_200_data_user:
      type: object
      properties:
        updated_at:
          type: string
        name:
          type: string
        created_at:
          type: string
        email_verified_at:
          type: string
        id:
          type: integer
        deleted_at: {}
        email:
          type: string
      example: null
    inline_response_200_5_data:
      type: object
      properties:
        carts:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_5_data_carts'
      example: null
    user_login_body:
      type: object
      properties:
        password:
          type: string
        email:
          type: string
    inline_response_200_4_data:
      type: object
      properties:
        id:
          type: integer
      example: null
    inline_response_422_2_errors:
      type: object
      properties:
        email:
          type: array
          items:
            type: string
      example: null
    inline_response_200:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/inline_response_200_data'
        status:
          type: string
    inline_response_422_2:
      type: object
      properties:
        message:
          type: string
        errors:
          $ref: '#/components/schemas/inline_response_422_2_errors'
    inline_response_422_1_errors:
      type: object
      properties:
        cart:
          type: array
          items:
            type: string
      example: null
    inline_response_400:
      type: object
      properties:
        error:
          type: string
    inline_response_422:
      type: object
      properties:
        message:
          type: string
        errors:
          $ref: '#/components/schemas/inline_response_422_errors'
    inline_response_422_1:
      type: object
      properties:
        message:
          type: string
        errors:
          $ref: '#/components/schemas/inline_response_422_1_errors'
    user_register_body:
      type: object
      properties:
        password:
          type: string
        name:
          type: string
        email:
          type: string
    inline_response_200_5_data_products:
      type: object
      properties:
        updated_at:
          type: string
        price:
          type: string
        name:
          type: string
        created_at:
          type: string
        sku:
          type: string
      example: null
    V1_cart_body:
      type: object
      properties:
        skus:
          type: array
          items:
            type: string
        name:
          type: string
        cart:
          type: integer
    inline_response_200_5:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/inline_response_200_5_data'
        status:
          type: string
    inline_response_200_6:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/inline_response_200_6_data'
        status:
          type: string
    cart_products_body:
      type: object
      properties:
        skus:
          type: array
          items:
            type: string
        cart:
          type: integer
    inline_response_200_6_data:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
      example: null
    inline_response_200_data:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/inline_response_200_data_user'
        token:
          type: string
      example: null
    inline_response_200_5_data_carts:
      type: object
      properties:
        updated_at:
          type: string
        user_id:
          type: integer
        name:
          type: string
        created_at:
          type: string
        id:
          type: integer
        deleted_at: {}
        products:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_5_data_products'
      example: null
    inline_response_200_3_data:
      type: object
      properties:
        message:
          type: string
      example: null
    inline_response_200_2_data_cart:
      type: object
      properties:
        updated_at:
          type: string
        user_id:
          type: integer
        name:
          type: string
        created_at:
          type: string
        id:
          type: integer
        products:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_5_data_products'
      example: null
    inline_response_422_errors:
      type: object
      properties:
        skus.0:
          type: array
          items:
            type: string
      example: null
    inline_response_200_1:
      type: object
      properties:
        message:
          type: string
    inline_response_200_2:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/inline_response_200_2_data'
        status:
          type: string
    inline_response_200_3:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/inline_response_200_3_data'
        status:
          type: string
    inline_response_200_4:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/inline_response_200_4_data'
        status:
          type: string
    inline_response_200_2_data:
      type: object
      properties:
        cart:
          $ref: '#/components/schemas/inline_response_200_2_data_cart'
      example: null
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://yourauthurl.com
          scopes:
            scope_name: Enter your scopes here
tags:
  - name: Product
  - name: User
  - name: Cart
