<?php

namespace Unit\Services;

use App\Services\Cart;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CartTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var Cart
     */
    protected $cart;

    /**
     * @return void
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cart = app()->make(Cart::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testDeleteNotFoundUser()
    {
        $cart = $this->cart->create('test');
        $this->assertDatabaseMissing('carts', ['id' => $cart->id + 1]);
        $this->expectException(ModelNotFoundException::class);
        $this->cart->delete($cart->id + 1);
    }

    public function testDeleteUser()
    {
        $cart = $this->cart->create('test');
        $this->assertDatabaseHas('carts', ['id' => $cart->id]);
        $this->assertEquals(true, $this->cart->delete($cart->id));
    }

    public function testCreateUser()
    {


    }


}
