<?php

namespace Unit\Services;

use App\Models\User;
use App\Services\Cart;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Validation\ValidationException;
use Tests\TestCase;

class CartTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var Cart
     */
    protected $cart;

    /**
     * @return void
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cart = app()->make(Cart::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testDeleteCartNotFound()
    {
        $user = User::factory()->create();

        $this->expectException(ValidationException::class);
        $this->cart->delete(1, $user->id);
    }

    public function testDeleteCartOfOtherUser()
    {
        $user1 = User::factory()->hasCarts(1)->create();
        $user2 = User::factory()->create();

        $this->expectException(ValidationException::class);
        $this->cart->delete($user1->carts()->first()->id, $user2->id);
    }

    public function testDeleteCartSuccess()
    {
        $user = User::factory()->hasCarts(1)->create();
        $cart = $user->carts()->first();

        $this->assertDatabaseHas('carts', ['id' => $cart->id]);
        $this->assertEquals(true, $this->cart->delete($cart->id, $user->id));
        $this->assertModelMissing($cart);
    }

    public function testCreateCart()
    {
        $user = User::factory()->create();

        $cart = $this->cart->create('name', $user->id);
        $this->assertModelExists($cart);
    }


}
